import axios from "axios";
import Head from 'next/head'
import { useRouter } from "next/router";
import { useEffect, useState } from "react"

export default function ProductDetail(props) {
  const { content, relatedProduct } = props
  const [loading, setLoading] = useState(true)
  const router = useRouter()

  const formatRp = (number) => {
    return new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR"
    }).format(number);
  }

  useEffect(() => {
    setTimeout(() => {
      setLoading(false)
    }, 400)
  }, [router])

  return (
    <div className="product-detail">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <span onClick={() => {
            setLoading(true)
            router.push(`/`)
          }} className="material-symbols-outlined">
            arrow_back
          </span>
          <h1>Product Detail</h1>
          <section>
            <div className="blur"></div>
            <section className="card-detail">
              <section className="first-section">
                <h3>{content.title}</h3>
                <p>{content.subtitle}</p>
                <section>
                  <section>
                    <img className="first" src={content.images.squarishURL} />
                  </section>
                  <section>
                    <img src={content.images.squarishURL} />
                  </section>
                  <section>
                    <img className="third" src={content.images.squarishURL} />
                  </section>
                </section>
              </section>
              <section className="second-section">
                <img src={content.images.squarishURL} />
              </section>
              <section className="third-section">
                <h4>Variant: </h4>
                <section>
                  {content.colorways.map((variant, index) => {
                    return (
                      <section key={index}>
                        <img src={variant.images.squarishURL} />
                      </section> 
                    )
                  })}
                </section>
                <h4>Price: </h4>
                <h2>{formatRp(content.price.fullPrice)}</h2>
                <button>
                  Add to cart
                </button>
              </section>
            </section>
          </section>
        </section>
        <section className="related-product">
          <h2>Related Product</h2>
          <section>
            {relatedProduct.map((item, index) => {
              return (<div key={index} className='card'>
              <div className='blur-effect'></div>
              <img src={item.images.squarishURL}/>
              <section>
                <h4 className='item-name'>{item.title}</h4>
                <h4>{formatRp(item.price.currentPrice)}</h4>
              </section>
              <section>
                <h5>Color:</h5>
                <h5 className='color-option'>{item.colorDescription}</h5>
              </section>
              <section className='button-container'>
                <button onClick={() => {
                  setLoading(true)
                  router.push(`/${item.id}`)
                }}>
                  Detail
                </button>
              </section>
            </div>)
            })}
          </section>
        </section>
      </main>
      {loading ?
        <section>
          <div className="lds-facebook"><div></div><div></div><div></div></div>
        </section>
        : null
      }
    </div>
  )
}

export async function getServerSideProps({ params }) {
  const { id } = params
  const getAsyncRequest = async (path) => {
    return await new Promise((resolve) => {
      axios.get(path)
      .then((res) => {
        resolve(res)
      })
      .catch((err) => {
        console.error(err)
        resolve(null)
      })
    })
  }

  let {data} = await getAsyncRequest(`https://63795f267419b414df8e1311.mockapi.io/api/v1/shoes-list/${id}`)

  let listProduct = await getAsyncRequest("https://63795f267419b414df8e1311.mockapi.io/api/v1/shoes-list")

  let relatedProduct = listProduct.data.filter((item) => item.id !== id).slice(0, 10)

  console.log(relatedProduct, relatedProduct.length);

  return {
    props: {
      content: data,
      relatedProduct
    }
  }
}