import axios from 'axios'
import Head from 'next/head'
import { useRouter } from "next/router";
import { useEffect, useState } from 'react'

export default function Home(props) {
  const [loading, setLoading] = useState(false)
  const router = useRouter()

  const formatRp = (number) => {
    return new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR"
    }).format(number);
  }

  useEffect(() => {
    setTimeout(() => {
      setLoading(false)
    }, 400)
  }, [router])

  return (
    <div className={'main-page'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <div>
          <div>
            <h1>Men&apos;s Shoes</h1>
          </div>
        </div>
        <section>
          {props.content.map((item, index) => {
            return (<div key={index} className='card'>
              <div className='blur-effect'></div>
              <img src={item.images.squarishURL}/>
              <section>
                <h4 className='item-name'>{item.title}</h4>
                <h4>{formatRp(item.price.currentPrice)}</h4>
              </section>
              <section>
                <h5>Color:</h5>
                <h5 className='color-option'>{item.colorDescription}</h5>
              </section>
              <section className='button-container'>
                <button onClick={() => {
                  setLoading(true)
                  router.push(`/${item.id}`)
                }}>
                  Detail
                </button>
              </section>
            </div>)
          })}
        </section>
      </main>
      {loading ?
        <section>
          <div className="lds-facebook"><div></div><div></div><div></div></div>
        </section>
        : null
      }
    </div>
  )
}

export async function getServerSideProps({ params }) {
  const getAsyncRequest = async (path) => {
    return await new Promise((resolve) => {
      axios.get(path)
      .then((res) => {
        resolve(res)
      })
      .catch((err) => {
        console.error(err)
        resolve(null)
      })
    })
  }

  let {data} = await getAsyncRequest("https://63795f267419b414df8e1311.mockapi.io/api/v1/shoes-list")
  console.log(data);
  return {
    props: {
      content: data
    }
  }
}


